[package]
name = "rhizome_anonymizer"
version = "0.1.0"
edition = "2024_07"
license = "MIT"

[dependencies]
starknet = "2.17.0"
openzeppelin = "3.0.0"
privacy = { git = "https://github.com/starkware-libs/starknet-privacy.git", branch = "main" }

[dev-dependencies]
snforge_std = "0.63.0"
assert_macros = "2.17.0"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true
